crudTask/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('task/', include('task.urls')),
]

task/urls.py
from django.urls import path, include
from . import views

#Creating Your urls here

app_name='tasks'

urlpatterns = [
    path('', views.home, name='home'),
    path('create/', views.create, name='create'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('signup/', views.sign_up, name='signup'),
]

task/models.py
from django.db import models

# Create your models here.

class ModelTask(models.Model):
    title_task = models.CharField(max_length=200)
    description_task = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    username = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.title_task

task/forms.py
from cProfile import label
from pyexpat import model
from attr import attr, attrs, field
from django import forms
from task.models import ModelTask

#Create Your Form Here

class FormTask(forms.ModelForm):

    class Meta:
        model = ModelTask
        fields = ['title_task', 'description_task', 'start_date', 'end_date']

task/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required, permission_required
from task.forms import FormTask
from task.models import ModelTask
from django.views.decorators.cache import cache_control
from django.contrib.auth.forms import UserCreationForm


# Create your views here.

@login_required(redirect_field_name='to', login_url='login')

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def home(request):

    username = request.user
    task = ModelTask.objects.filter(username=username).values()
    
    return render(request, 'home.html', {'tasks': task, "username": username})
    
@login_required(redirect_field_name='to', login_url='login/')
def create(request):

    form = FormTask()
    if request.method == 'POST':

        title = request.POST.get('title_task')
        description = request.POST.get('description_task')
        start = request.POST.get('start_date')
        end = request.POST.get('end_date')
        username = request.user

        ModelTask.objects.create(title_task=title, description_task=description, start_date=start, end_date=end, username=username)
        
        return redirect('tasks:home')
    else:
        return render(request, 'create.html', {'form': form})


@login_required(redirect_field_name='to', login_url='login')
def delete(request, id):

    task = ModelTask.objects.get(pk=id)
    task.delete()
    return redirect('tasks:home')


@login_required(redirect_field_name='to', login_url='login')
def update(request, id):
    
    task = get_object_or_404(ModelTask, pk=id)
    form = FormTask(request.POST, instance=task)

    if request.method == 'POST':
        task.title_task = request.POST.get('title_task')
        task.description_task = request.POST.get('description_task')
        task.start_date = request.POST.get('start_date')
        task.end_date = request.POST.get('end_date')
        task.save()

        return redirect('tasks:home')

    else:
        return render(request, 'update.html', {'form': form, 'task': task})

def sign_up(request):
    
    
    # username = request.POST.get('username')
    password1 = request.POST.get('password1')
    password2 = request.POST.get('password2')
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

task/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% block style %}{% endblock %}
    {% block title %}
        <title>Base Template</title>
    {% endblock %}
</head>
<body>
    {% autoescape on %}
    {% block content %}
    {% endblock %}
    {% endautoescape %}
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
 integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>

task/templates/pages/create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Create Task</title>
{% endblock %}

{% block content %}

    <div class="container card row mt-5 fw-lighter" style="text-align: ceneter;margin-left:100px">
    
        <div class="mb-3 text-center">
            <h2 class="fw-lighter">Add Task</h2>
        </div>
        <form action="/task/create/" method="post" class="row g-1">
            {% csrf_token %}
    
            <div class="mb-3">
                <div class="col-md-12 text-center">
                    <label for="id_title_task" class="d-flex form-label">Title task:</label>
                    <input type="text" class="form-control d-flex" id="exampleFormControlInput1" name="title_task" value="{{task.title_task}}" maxlength="200" required="" spellcheck="false" data-ms-editor="true">
                </div>
            </div>
    
            <div class="mb-3">
                <div class="col-md-12">
                    <label for="id_description_task" class="form-label">Description task:</label>
                    <textarea name="description_task" class="form-control col-sm-1" required="" id="exampleFormControlTextarea1" spellcheck="false" data-ms-editor="true">{{task.description_task}}           
                    </textarea>
                </div>
            </div>
    
            <div class="mb-3">
                <div class="col-md-12">
                    <label for="id_start_date" class="form-label">Start date:</label>
                    <input type="text" name="start_date" class="form-control" id="exampleFormControlInput1" placeholder="0000-00-00 Date format" required="" spellcheck="false" data-ms-editor="true">
                </div>
            </div>
            
            <div class="mb-3">
                <div class="col-md-12">
                    <label for="id_end_date" class="form-label">End date:</label>
                    <input type="text" name="end_date" class="form-control" id="exampleFormControlInput1" placeholder="0000-00-00 Date Format" required="" spellcheck="false" data-ms-editor="true">
                </div>
            </div>
            <div class="d-grid gap-2 col-4 mx-auto">
                <div class="col-md-6"></div>
                    <input type="submit" class="btn btn-dark text-transparent mb-2 fw-light" value="Add">
                </div>
            </div>
        </form>
    </div>

    <div>
        <a href="{% url 'tasks:home' %}" class="fw-lighter text-dark" 
        style="font-size: 1.3rem;position: fixed;top: 0px;left: 100px;text-decoration:none;">
            <i class="fa fa-arrow-circle-left text-dark"></i>Task List</a>
    </div>
{% endblock %}

task/templates/pages/home.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static '/task/style/style.css' %}">
{% endblock %}

{% block title %}
    <title>Home Task</title>
{% endblock %}

{% block content %}
    <div class="container-fluid card p-3 mt-3 fw-lighter">
        {% if request.user.is_authenticated %}
            <p>
                <a href="{% url 'logout' %}" class="nav-links"><span>Logout</span></a>
                <a href="{% url 'password_change' %}" class="nav-links"><span>Change password</span></a>
            </p>
        {% endif %}
        <div class="text-center text-white-50 bg-dark p-1" style="width:30%; text-align: center;margin: 10px auto;border-radius: 5px;">
            <h1 class="border-bottom border-info fw-light">List of Task</h1>
        </div>
            <div class="row align-items-center lh-5 rounded-1 p-3 mb-2 bg-dark text-white sticky-top ">
                <div class="col-2 border-1 border-start border-info">
                    Task
                </div>
                <div class="col-4 border-1 border-start border-info">
                  Description
                </div>
                <div class="col-2 text-center border-1 border-start border-info">
                  Start Date
                </div>
                <div class="col-2 text-center border-1 border-start border-info">
                    End Date
                </div>
                <div class="col text-center border-1 border-start border-info">
                    Delete
                </div>
                <div class="col text-center border-1 border-start border-end border-info">
                    Update
                </div>
              </div>
            {% for task in tasks reversed %}
              <div class="row align-items-center border-bottom border-info p-2 effect">
                <div class="col-2">
                    {{task.title_task}}
                </div>
                <div class="col-4">
                    {{task.description_task}}
                </div>
                <div class="col-2 text-center">
                    {{task.start_date}}
                </div>
                <div class="col-2 text-center">
                    {{task.end_date}}
                </div>
                <div class="col text-center">
                    <a href="{% url 'tasks:delete' task.id %}"><i class="fa fa-trash-o text-dark"></i></a>
                </div>
                <div class="col text-center">
                    <a href="{% url 'tasks:update' task.id %}"><i class="fa fa-undo text-dark"></i></a>
                </div>
              </div>
            {% endfor %}  
        </div>
        <div id="add-task-container">
            <a href="{% url 'tasks:create' %}" id="add-task" class="text-white-50 fw-light">Add Task</a>
        </div>
    </div>
{% endblock %}

task/templates/pages/update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Update Task</title>
{% endblock %}

{% block content %}
    <div class="container card row fw-light mt-5" style="text-align: ceneter;margin-left:100px">
        <div class="mb-3 text-center">
            <h2 class="fw-light">Update Task</h2>
        </div>
        <form action="/task/update/{{task.id}}" method="post" class="row g-1">
            {% csrf_token %}
    
            <div class="mb-3">
                <div class="col-md-12 text-center">
                    <label for="id_title_task" class="d-flex form-label">Title task:</label>
                    <input type="text" class="form-control d-flex" id="exampleFormControlInput1" name="title_task" value="{{task.title_task}}" maxlength="200" required="" spellcheck="false" data-ms-editor="true">
                </div>
            </div>
    
            <div class="mb-3">
                <div class="col-md-12">
                    <label for="id_description_task" class="form-label">Description task:</label>
                    <textarea name="description_task" class="form-control col-sm-1" required="" id="exampleFormControlTextarea1" spellcheck="false" data-ms-editor="true">{{task.description_task}}           
                    </textarea>
                </div>
            </div>
    
            <div class="mb-3">
                <div class="col-md-12">
                    <label for="id_start_date" class="form-label">Start date:</label>
                    <input type="text" name="start_date" class="form-control" id="exampleFormControlInput1" value="{{task.start_date|date:'Y-m-d'}}" required="" spellcheck="false" data-ms-editor="true">
                </div>
            </div>
            
            <div class="mb-3">
                <div class="col-md-12">
                    <label for="id_end_date" class="form-label">End date:</label>
                    <input type="text" name="end_date" class="form-control" id="exampleFormControlInput1" value="{{task.end_date|date:'Y-m-d'}}" required="" spellcheck="false" data-ms-editor="true">
                </div>
            </div>
            <div class="d-grid gap-2 col-4 mx-auto">
                <div class="col-md-6"></div>
                    <input type="submit" class="btn btn-dark text-transparent mb-2 fw-light" value="Update">
                </div>
            </div>
        </form>
    </div>
    
    <div>
        <a href="{% url 'tasks:home' %}" class="fw-lighter text-dark" 
        style="font-size: 1.3rem;position: fixed;top: 0px;left: 100px;text-decoration:none;">
            <i class="fa fa-arrow-circle-left text-dark"></i>Task List</a>
    </div>
   
{% endblock %}